export const ChaosBoons = {
  Abyssal: 'Abyssal',
  Addled: 'Addled',
  Affluence: 'Affluence',
  Ambush: 'Ambush',
  Assault: 'Assault',
  Atrophic: 'Atrophic',
  Caustic: 'Caustic',
  Defiance: 'Defiance',
  Eclipse: 'Eclipse',
  Enshrouded: 'Enshrouded',
  Excruciating: 'Excruciating',
  Favor: 'Favor',
  Flayed: 'Flayed',
  Flourish: 'Flourish',
  Grasp: 'Grasp',
  Halting: 'Halting',
  Lunge: 'Lunge',
  Maimed: 'Maimed',
  Pauper: 'Pauper',
  Roiling: 'Roiling',
  Shot: 'Shot',
  Slippery: 'Slippery',
  Slothful: 'Slothful',
  Soul: 'Soul',
  Strike: 'Strike',
} as const;
