export const Descriptions = {
  Attack: 'Attack',
  Armor: 'Armor',
  Blade_Rift: 'Blade Rift',
  Boons: 'Boons',
  Bosses: 'Bosses',
  Bull_Rush: 'Bull Rush',
  Call: 'Call',
  Cast_Ammo: 'Cast Ammo',
  Cast: 'Cast',
  Celestial_Sharanga: 'Celestial Sharanga',
  Chamber: 'Chamber',
  Chambers: 'Chambers',
  Charm: 'Charm',
  Chill: 'Chill',
  Claws_of_Enkindu: 'Claws of Enkindu',
  Coin: 'Coin',
  Critical: 'Critical',
  Curse: 'Curse',
  Darkness: 'Darkness',
  Dash_Attack: 'Dash-Attack',
  Dash_Strike: 'Dash-Strike',
  Dash_Upper: 'Dash Upper',
  Dash: 'Dash',
  Death_Defiance: 'Death Defiance',
  Decay: 'Decay',
  Deflect: 'Deflect',
  Dodge: 'Dodge',
  Doom: 'Doom',
  Encounter: 'Encounter',
  Encounters: 'Encounters',
  Exposed: 'Exposed',
  Festive_Fog: 'Festive Fog',
  Fishing_Point: 'Fishing Point',
  Flood_Shot: 'Flood Shot', // outputs as 'Cast'
  Fountain: 'Fountain',
  Frost_Fair_Blade: 'Frost Fair Blade',
  Gemstone: 'Gemstone',
  God_Gauge: 'God Gauge',
  Hangover: 'Hangover',
  Healing: 'Healing',
  Health_Up: 'Health Up',
  Health: 'Health',
  Hellfire: 'Hellfire',
  Holy_Excalibur: 'Holy Excalibur',
  Igneus_Eden: 'Igneus Eden',
  Impervious: 'Impervious',
  Inferno_Bomb: 'Inferno Bomb',
  Jolted: 'Jolted',
  Magnetic_Cutter: 'Magnetic Cutter',
  Maim: 'Maim',
  Marked: 'Marked',
  Naeglings_Board: 'Naegling\'s Board',
  Nectar: 'Nectar',
  NUMBERc: 'a certain amount of',
  NUMBERl: 'less',
  NUMBERm: 'more',
  NUMBERn: 'number of',
  NUMBERp: 'a higher percent',
  Poms_of_Power: 'Poms of Power',
  Punishing_Sweep: 'Punishing Sweep',
  Raging_Rush: 'Raging Rush',
  Rarity: 'Rarity',
  Reload: 'Reload',
  Revenge: 'Revenge',
  Rupture: 'Rupture',
  Shared_Suffering: 'Shared Suffering',
  Special: 'Special',
  Spin_Attack: 'Spin Attack',
  Stubborn_Defiance: 'Stubborn Defiance',
  Sturdy: 'Sturdy',
  Traps: 'Traps',
  Weak: 'Weak',
} as const;
