export const Icons = {
  Active: 'Active',
  Ambrosia: 'Ambrosia',
  Anvil_of_Fates: 'Anvil of Fates',
  Aspect_Unlocks: 'Aspect Unlocks',
  Attack: 'Attack',
  Blessing: 'Blessing',
  Bloodstone: 'Bloodstone',
  Call: 'Call',
  Cast: 'Cast',
  Centaur_Heart: 'Centaur Heart',
  Charons_Obol: 'Charon\'s Obol',
  Chthonic_Key: 'Chthonic Key',
  Codex_Filled: 'Codex Filled',
  Codex_Locked: 'Codex Locked',
  Contractor_Item: 'Contractor Item',
  Curse: 'Curse',
  Daedalus_Hammer: 'Daedalus Hammer',
  Darkness: 'Darkness',
  Dash: 'Dash',
  Diamond: 'Diamond',
  Extreme_Measures: 'Extreme Measures',
  Fated_List: 'Fated List',
  Gemstone: 'Gemstone',
  Heat: 'Heat',
  Inactive: 'Inactive',
  Infernal_Gate: 'Infernal Gate',
  Item: 'Item',
  Keepsake_Items: 'Keepsake Items',
  Keepsakes: 'Keepsakes',
  Legendary: 'Legendary',
  Loyalty_Card: 'Loyalty Card',
  Nectar: 'Nectar',
  Other: 'Other',
  Pom_of_Power: 'Pom of Power',
  Prophecy_Foretold: 'Prophecy Foretold',
  Prophecy_Not_Foretold: 'Prophecy Not Foretold',
  Requires: 'Requires',
  Restricted: 'Restricted',
  Rod_of_Fishing: 'Rod of Fishing',
  Skeleton_Key: 'Skeleton Key',
  Special: 'Special',
  Status_Curse: 'Status Curse',
  Swap: 'Swap',
  Trove_Tracker: 'Trove Tracker',
} as const;
