export const Companions = {
  Antos: 'Antos',
  Battie: 'Battie',
  Fidi: 'Fidi',
  Mort: 'Mort',
  Rib: 'Rib',
  Shady: 'Shady',
} as const;

export const Keepsakes = {
  Adamant_Arrowhead: 'Adamant Arrowhead',
  Black_Shawl: 'Black Shawl',
  Blood_Filled_Vial: 'Blood Filled Vial',
  Bone_Hourglass: 'Bone Hourglass',
  Broken_Spearpoint: 'Broken Spearpoint',
  Chthonic_Coin_Purse: 'Chthonic Coin Purse',
  Conch_Shell: 'Conch Shell',
  Cosmic_Egg: 'Cosmic Egg',
  Distant_Memory: 'Distant Memory',
  Eternal_Rose: 'Eternal Rose',
  Evergreen_Acorn: 'Evergreen Acorn',
  Frostbitten_Horn: 'Frostbitten Horn',
  Harpy_Feather_Duster: 'Harpy Feather Duster',
  Lambent_Plume: 'Lambent Plume',
  Lucky_Tooth: 'Lucky Tooth',
  Myrmidon_Bracer: 'Myrmidon Bracer',
  Old_Spiked_Collar: 'Old Spiked Collar',
  Overflowing_Cup: 'Overflowing Cup',
  Owl_Pendant: 'Owl Pendant',
  Pierced_Butterfly: 'Pierced Butterfly',
  Pom_Blossom: 'Pom Blossom',
  Shattered_Shackle: 'Shattered Shackle',
  Sigil_of_the_Dead: 'Sigil of the Dead',
  Skull_Earring: 'Skull Earring',
  Thunder_Signet: 'Thunder Signet',
} as const;
