export const Aspects = {
  Aspect_of_Arthur: 'Aspect of Arthur',
  Aspect_of_Nemesis: 'Aspect of Nemesis',
  Aspect_of_Poseidon: 'Aspect of Poseidon',
  Aspect_of_Zagreus_Blade: 'Aspect of Zagreus (Blade)',
  Aspect_of_Chiron: 'Aspect of Chiron',
  Aspect_of_Hera: 'Aspect of Hera',
  Aspect_of_Rama: 'Aspect of Rama',
  Aspect_of_Zagreus_Bow: 'Aspect of Zagreus (Bow)',
  Aspect_of_Demeter: 'Aspect of Demeter',
  Aspect_of_Gilgamesh: 'Aspect of Gilgamesh',
  Aspect_of_Talos: 'Aspect of Talos',
  Aspect_of_Zagreus_Fists: 'Aspect of Zagreus (Fists)',
  Aspect_of_Eris: 'Aspect of Eris',
  Aspect_of_Hestia: 'Aspect of Hestia',
  Aspect_of_Lucifer: 'Aspect of Lucifer',
  Aspect_of_Zagreus_Rail: 'Aspect of Zagreus (Rail)',
  Aspect_of_Beowulf: 'Aspect of Beowulf',
  Aspect_of_Chaos: 'Aspect of Chaos',
  Aspect_of_Zagreus_Shield: 'Aspect of Zagreus (Shield)',
  Aspect_of_Zeus: 'Aspect of Zeus',
  Aspect_of_Achilles: 'Aspect of Achilles',
  Aspect_of_Guan_Yu: 'Aspect of Guan Yu',
  Aspect_of_Hades: 'Aspect of Hades',
  Aspect_of_Zagreus_Spear: 'Aspect of Zagreus (Spear)',
} as const;

export const Upgrades = {
  Bow_Rama_Repulse_Shot: 'Bow Rama Repulse Shot',
  Breaching_Cross: 'Breaching Cross',
  Breaching_Rush: 'Breaching Rush',
  Breaching_Skewer: 'Breaching Skewer',
  Breaching_Slash: 'Breaching Slash',
  Chain_Shot: 'Chain Shot',
  Chain_Skewer: 'Chain Skewer',
  Charged_Flight: 'Charged Flight',
  Charged_Shot: 'Charged Shot',
  Charged_Skewer: 'Charged Skewer',
  Charged_Volley: 'Charged Volley',
  Cluster_Bomb: 'Cluster Bomb',
  Colossus_Knuckle: 'Colossus Knuckle',
  Concentrated_Beam: 'Concentrated Beam',
  Concentrated_Fire: 'Concentrated Fire',
  Concentrated_Knuckle: 'Concentrated Knuckle',
  Concentrated_Volley: 'Concentrated Volley',
  Cooling_Chamber: 'Cooling Chamber',
  Cruel_Thrust: 'Cruel Thrust',
  Cursed_Slash: 'Cursed Slash',
  Dash_Nova: 'Dash Nova',
  Dashing_Flight: 'Dashing Flight',
  Dashing_Wallop: 'Dashing Wallop',
  Delta_Chamber: 'Delta Chamber',
  Double_Edge: 'Double Edge',
  Double_Nova: 'Double Nova',
  Draining_Cutter: 'Draining Cutter',
  Dread_Flight: 'Dread Flight',
  Empowering_Flight: 'Empowering Flight',
  Empowering_Nova: 'Empowering Nova',
  Eternal_Chamber: 'Eternal Chamber',
  Exploding_Launcher: 'Exploding Launcher',
  Explosive_Fire: 'Explosive Fire',
  Explosive_Return: 'Explosive Return',
  Explosive_Shot: 'Explosive Shot',
  Explosive_Upper: 'Explosive Upper',
  Extending_Jab: 'Extending Jab',
  Ferocious_Guard: 'Ferocious Guard',
  Flaring_Spin: 'Flaring Spin',
  Flash_Fire: 'Flash Fire',
  Flurry_Fire: 'Flurry Fire',
  Flurry_Jab: 'Flurry Jab',
  Flurry_Shot: 'Flurry Shot',
  Flurry_Slash: 'Flurry Slash',
  Flying_Cutter: 'Flying Cutter',
  Greater_Inferno: 'Greater Inferno',
  Hazard_Bomb: 'Hazard Bomb',
  Heavy_Knuckle: 'Heavy Knuckle',
  Heavy_Slug: 'Heavy Slug',
  Hoarding_Slash: 'Hoarding Slash',
  Inescapable_Blast: 'Inescapable Blast',
  Invigorating_Blast: 'Invigorating Blast',
  Javelin_Throw: 'Javelin Throw',
  Kinetic_Launcher: 'Kinetic Launcher',
  Long_Knuckle: 'Long Knuckle',
  Massive_Spin: 'Massive Spin',
  Minotaur_Rush: 'Minotaur Rush',
  Mirage_Flight: 'Mirage Flight',
  Peerless_Parry: 'Peerless Parry',
  Perfect_Shot: 'Perfect Shot',
  Piercing_Fire: 'Piercing Fire',
  Piercing_Volley: 'Piercing Volley',
  Piercing_Wave: 'Piercing Wave',
  Point_Blank_Shot: 'Point-Blank Shot',
  Pulverizing_Blow: 'Pulverizing Blow',
  Quake_Cutter: 'Quake Cutter',
  Quick_Spin: 'Quick Spin',
  Relentless_Volley: 'Relentless Volley',
  Rending_Claws: 'Rending Claws',
  Ricochet_Fire: 'Ricochet Fire',
  Rocket_Bomb: 'Rocket Bomb',
  Rolling_Knuckle: 'Rolling Knuckle',
  Rush_Kick: 'Rush Kick',
  Seeking_Fire: 'Seeking Fire',
  Serrated_Point: 'Serrated Point',
  Shadow_Slash: 'Shadow Slash',
  Sniper_Shot: 'Sniper Shot',
  Spear_Winged_Serpent: 'Spear Winged Serpent',
  Spread_Fire: 'Spread Fire',
  Sudden_Rush: 'Sudden Rush',
  Super_Nova: 'Super Nova',
  Sword_Greater_Consecration: 'Sword Greater Consecration',
  Targeting_System: 'Targeting System',
  Triple_Beam: 'Triple Beam',
  Triple_Bomb: 'Triple Bomb',
  Triple_Jab: 'Triple Jab',
  Triple_Shot: 'Triple Shot',
  Twin_Shot: 'Twin Shot',
  Unyielding_Defense: 'Unyielding Defense',
  Vicious_Skewer: 'Vicious Skewer',
  World_Splitter: 'World Splitter',
} as const;

export const Weapons = {
  Adamant_Rail: 'Adamant Rail',
  Eternal_Spear: 'Eternal Spear',
  Heart_Seeker_Bow: 'Heart Seeker Bow',
  Shield_of_Chaos: 'Shield of Chaos',
  Stygian_Blade: 'Stygian Blade',
  Twin_Fists: 'Twin Fists',
} as const;
