export const Boons = {
  Abyssal: 'Abyssal',
  Addled: 'Addled',
  Affluence: 'Affluence',
  After_Party: 'After Party',
  Ambush: 'Ambush',
  Aphrodites_Aid: 'Aphrodite\'s Aid',
  Arctic_Blast: 'Arctic Blast',
  Ares_Aid: 'Ares\' Aid',
  Artemis_Aid: 'Artemis\' Aid',
  Assault: 'Assault',
  Athenas_Aid: 'Athena\'s Aid',
  Atrophic: 'Atrophic',
  Auto_Reload: 'Auto Reload',
  Bad_Influence: 'Bad Influence',
  Bad_News: 'Bad News',
  Battle_Rage: 'Battle Rage',
  Billowing_Strength: 'Billowing Strength',
  Black_Metal: 'Black Metal',
  Black_Out: 'Black Out',
  Blade_Dash: 'Blade Dash',
  Blessing: 'Blessing',
  Blinding_Flash: 'Blinding Flash',
  Blizzard_Shot: 'Blizzard Shot',
  Blood_Frenzy: 'Blood Frenzy',
  Blown_Kiss: 'Blown Kiss',
  Boiling_Point: 'Boiling Point',
  Bolt_Shot: 'Bolt Shot',
  Bow_Rama_Repulse_Shot: 'Bow Rama Repulse Shot',
  Breaching_Cross: 'Breaching Cross',
  Breaching_Rush: 'Breaching Rush',
  Breaching_Skewer: 'Breaching Skewer',
  Breaching_Slash: 'Breaching Slash',
  Breaking_Wave: 'Breaking Wave',
  Brilliant_Riposte: 'Brilliant Riposte',
  Broken_Resolve: 'Broken Resolve',
  Bronze_Skin: 'Bronze Skin',
  Calculated_Risk: 'Calculated Risk',
  Caustic: 'Caustic',
  Chain_Lightning: 'Chain Lightning',
  Chain_Shot: 'Chain Shot',
  Chain_Skewer: 'Chain Skewer',
  Charged_Flight: 'Charged Flight',
  Charged_Shot: 'Charged Shot',
  Charged_Skewer: 'Charged Skewer',
  Charged_Volley: 'Charged Volley',
  Clean_Kill: 'Clean Kill',
  Clouded_Judgement: 'Clouded Judgement',
  Cluster_Bomb: 'Cluster Bomb',
  Cold_Embrace: 'Cold Embrace',
  Cold_Fusion: 'Cold Fusion',
  Colossus_Knuckle: 'Colossus Knuckle',
  Concentrated_Beam: 'Concentrated Beam',
  Concentrated_Fire: 'Concentrated Fire',
  Concentrated_Knuckle: 'Concentrated Knuckle',
  Concentrated_Volley: 'Concentrated Volley',
  Cooling_Chamber: 'Cooling Chamber',
  Cruel_Thrust: 'Cruel Thrust',
  Crush_Shot: 'Crush Shot',
  Crystal_Beam: 'Crystal Beam',
  Crystal_Clarity: 'Crystal Clarity',
  Curse: 'Curse',
  Curse_of_Agony: 'Curse of Agony',
  Curse_of_Drowning: 'Curse of Drowning',
  Curse_of_Longing: 'Curse of Longing',
  Curse_of_Nausea: 'Curse of Nausea',
  Curse_of_Pain: 'Curse of Pain',
  Curse_of_Vengeance: 'Curse of Vengeance',
  Cursed_Slash: 'Cursed Slash',
  Daedalus_Upgrades: 'Daedalus Upgrades',
  Dash_Nova: 'Dash Nova',
  Dashing_Flight: 'Dashing Flight',
  Dashing_Wallop: 'Dashing Wallop',
  Deadly_Flourish: 'Deadly Flourish',
  Deadly_Reversal: 'Deadly Reversal',
  Deadly_Strike: 'Deadly Strike',
  Deathless_Stand: 'Deathless Stand',
  Defiance: 'Defiance',
  Delta_Chamber: 'Delta Chamber',
  Demeters_Aid: 'Demeter\'s Aid',
  Different_League: 'Different League',
  Dionysus_Aid: 'Dionysus\' Aid',
  Dire_Misfortune: 'Dire Misfortune',
  Divine_Dash: 'Divine Dash',
  Divine_Flourish: 'Divine Flourish',
  Divine_Protection: 'Divine Protection',
  Divine_Strike: 'Divine Strike',
  Double_Edge: 'Double Edge',
  Double_Nova: 'Double Nova',
  Double_Strike: 'Double Strike',
  Draining_Cutter: 'Draining Cutter',
  Dread_Flight: 'Dread Flight',
  Drunken_Dash: 'Drunken Dash',
  Drunken_Flourish: 'Drunken Flourish',
  Drunken_Strike: 'Drunken Strike',
  Dual_Shot: 'Dual Shot',
  Dying_Lament: 'Dying Lament',
  Eclipse: 'Eclipse',
  Electric_Shot: 'Electric Shot',
  Empowering_Flight: 'Empowering Flight',
  Empowering_Nova: 'Empowering Nova',
  Empty_Inside: 'Empty Inside',
  Engulfing_Vortex: 'Engulfing Vortex',
  Enshrouded: 'Enshrouded',
  Eternal_Chamber: 'Eternal Chamber',
  Exclusive_Access: 'Exclusive Access',
  Excruciating: 'Excruciating',
  Exit_Wounds: 'Exit Wounds',
  Exploding_Launcher: 'Exploding Launcher',
  Explosive_Fire: 'Explosive Fire',
  Explosive_Return: 'Explosive Return',
  Explosive_Shot: 'Explosive Shot',
  Explosive_Upper: 'Explosive Upper',
  Extending_Jab: 'Extending Jab',
  Favor: 'Favor',
  Ferocious_Guard: 'Ferocious Guard',
  Flaring_Spin: 'Flaring Spin',
  Flash_Fire: 'Flash Fire',
  Flayed: 'Flayed',
  Flood_Shot: 'Flood Shot',
  Flourish: 'Flourish',
  Flurry_Cast: 'Flurry Cast',
  Flurry_Fire: 'Flurry Fire',
  Flurry_Jab: 'Flurry Jab',
  Flurry_Shot: 'Flurry Shot',
  Flurry_Slash: 'Flurry Slash',
  Flying_Cutter: 'Flying Cutter',
  Freezing_Vortex: 'Freezing Vortex',
  Frost_Flourish: 'Frost Flourish',
  Frost_Strike: 'Frost Strike',
  Frozen_Touch: 'Frozen Touch',
  Fully_Loaded: 'Fully Loaded',
  Glacial_Glare: 'Glacial Glare',
  Grasp: 'Grasp',
  Greater_Evasion: 'Greater Evasion',
  Greater_Haste: 'Greater Haste',
  Greater_Inferno: 'Greater Inferno',
  Greater_Recall: 'Greater Recall',
  Greatest_Reflex: 'Greatest Reflex',
  Hades_Aid: 'Hades%27 Aid',
  Halting: 'Halting',
  Hazard_Bomb: 'Hazard Bomb',
  Heart_Rend: 'Heart Rend',
  Heart_of_Stone: 'Heart of Stone',
  Heartbreak_Flourish: 'Heartbreak Flourish',
  Heartbreak_Strike: 'Heartbreak Strike',
  Heavens_Vengeance: 'Heaven\'s Vengeance',
  Heavy_Knuckle: 'Heavy Knuckle',
  Heavy_Slug: 'Heavy Slug',
  Hide_Breaker: 'Hide Breaker',
  High_Tolerance: 'High Tolerance',
  High_Voltage: 'High Voltage',
  Hoarding_Slash: 'Hoarding Slash',
  Holy_Shield: 'Holy Shield',
  Huge_Catch: 'Huge Catch',
  Hungry_Blades: 'Hungry Blades',
  Hunter_Dash: 'Hunter Dash',
  Hunter_Instinct: 'Hunter Instinct',
  Hunters_Mark: 'Hunter\'s Mark',
  Hunting_Blades: 'Hunting Blades',
  Hydraulic_Might: 'Hydraulic Might',
  Hyper_Sprint: 'Hyper Sprint',
  Ice_Wine: 'Ice Wine',
  Impending_Doom: 'Impending Doom',
  Inescapable_Blast: 'Inescapable Blast',
  Invigorating_Blast: 'Invigorating Blast',
  Javelin_Throw: 'Javelin Throw',
  Killing_Freeze: 'Killing Freeze',
  Kinetic_Launcher: 'Kinetic Launcher',
  Last_Stand: 'Last Stand',
  Life_Affirmation: 'Life Affirmation',
  Lightning_Flourish: 'Lightning Flourish',
  Lightning_Phalanx: 'Lightning Phalanx',
  Lightning_Reflexes: 'Lightning Reflexes',
  Lightning_Rod: 'Lightning Rod',
  Lightning_Strike: 'Lightning Strike',
  Long_Knuckle: 'Long Knuckle',
  Low_Tolerance: 'Low Tolerance',
  Lunge: 'Lunge',
  Maimed: 'Maimed',
  Massive_Spin: 'Massive Spin',
  Merciful_End: 'Merciful End',
  Minotaur_Rush: 'Minotaur Rush',
  Mirage_Flight: 'Mirage Flight',
  Mirage_Shot: 'Mirage Shot',
  Mistral_Dash: 'Mistral Dash',
  Nourished_Soul: 'Nourished Soul',
  Numbing_Sensation: 'Numbing Sensation',
  Oceans_Bounty: 'Ocean\'s Bounty',
  Parting_Shot: 'Parting Shot',
  Passing_Through: 'Passing Through',
  Passion_Dash: 'Passion Dash',
  Pauper: 'Pauper',
  Peer_Pressure: 'Peer Pressure',
  Peerless_Parry: 'Peerless Parry',
  Perfect_Shot: 'Perfect Shot',
  Phalanx_Shot: 'Phalanx Shot',
  Piercing_Fire: 'Piercing Fire',
  Piercing_Volley: 'Piercing Volley',
  Piercing_Wave: 'Piercing Wave',
  Point_Blank_Shot: 'Point-Blank Shot',
  Poseidons_Aid: 'Poseidon\'s Aid',
  Positive_Outlook: 'Positive Outlook',
  Premium_Vintage: 'Premium Vintage',
  Pressure_Points: 'Pressure Points',
  Proud_Bearing: 'Proud Bearing',
  Pulverizing_Blow: 'Pulverizing Blow',
  Quake_Cutter: 'Quake Cutter',
  Quick_Favor: 'Quick Favor',
  Quick_Recovery: 'Quick Recovery',
  Quick_Reload: 'Quick Reload',
  Quick_Spin: 'Quick Spin',
  Rare_Crop: 'Rare Crop',
  Ravenous_Will: 'Ravenous Will',
  Razor_Shoals: 'Razor Shoals',
  Relative_Speed: 'Relative Speed',
  Relentless_Volley: 'Relentless Volley',
  Remedy: 'Remedy',
  Rending_Claws: 'Rending Claws',
  Ricochet_Fire: 'Ricochet Fire',
  Rip_Current: 'Rip Current',
  Rocket_Bomb: 'Rocket Bomb',
  Roiling: 'Roiling',
  Rolling_Knuckle: 'Rolling Knuckle',
  Rush_Delivery: 'Rush Delivery',
  Rush_Kick: 'Rush Kick',
  Scintillating_Feast: 'Scintillating Feast',
  Sea_Storm: 'Sea Storm',
  Second_Wave: 'Second Wave',
  Second_Wind: 'Second Wind',
  Seeking_Fire: 'Seeking Fire',
  Serrated_Point: 'Serrated Point',
  Shadow_Slash: 'Shadow Slash',
  Shatter_Shot: 'Shatter Shot',
  Shot: 'Shot',
  Side_Hustle: 'Side Hustle',
  Slicing_Shot: 'Slicing Shot',
  Slippery: 'Slippery',
  Slothful: 'Slothful',
  Smoldering_Air: 'Smoldering Air',
  Sniper_Shot: 'Sniper Shot',
  Snow_Burst: 'Snow Burst',
  Soul: 'Soul',
  Spear_Winged_Serpent: 'Spear Winged Serpent',
  Splitting_Bolt: 'Splitting Bolt',
  Splitting_Headache: 'Splitting Headache',
  Spread_Fire: 'Spread Fire',
  Stabbing: 'Stabbing',
  Static_Discharge: 'Static Discharge',
  Storm_Lightning: 'Storm Lightning',
  Strike: 'Strike',
  Strong_Drink: 'Strong Drink',
  Stubborn_Roots: 'Stubborn Roots',
  Sudden_Rush: 'Sudden Rush',
  Sunken_Treasure: 'Sunken Treasure',
  Super_Nova: 'Super Nova',
  Support_Fire: 'Support Fire',
  Sure_Footing: 'Sure Footing',
  Sweet_Nectar: 'Sweet Nectar',
  Sweet_Surrender: 'Sweet Surrender',
  Swift_Flourish: 'Swift Flourish',
  Swift_Strike: 'Swift Strike',
  Sword_Greater_Consecration: 'Sword Greater Consecration',
  Targeting_System: 'Targeting System',
  Tempest_Flourish: 'Tempest Flourish',
  Tempest_Strike: 'Tempest Strike',
  Thunder_Dash: 'Thunder Dash',
  Thunder_Flourish: 'Thunder Flourish',
  Tidal_Dash: 'Tidal Dash',
  Tidal_Surge: 'Tidal Surge',
  Triple_Beam: 'Triple Beam',
  Triple_Bomb: 'Triple Bomb',
  Triple_Jab: 'Triple Jab',
  Triple_Shot: 'Triple Shot',
  Trippy_Flare: 'Trippy Flare',
  Trippy_Shot: 'Trippy Shot',
  True_Shot: 'True Shot',
  Twin_Shot: 'Twin Shot',
  Typhoons_Fury: 'Typhoon\'s Fury',
  Unhealthy_Fixation: 'Unhealthy Fixation',
  Unshakable_Mettle: 'Unshakable Mettle',
  Unyielding_Defense: 'Unyielding Defense',
  Urge_to_Kill: 'Urge to Kill',
  Vast_Riches: 'Vast Riches',
  Vengeful_Mood: 'Vengeful Mood',
  Vicious_Cycle: 'Vicious Cycle',
  Vicious_Skewer: 'Vicious Skewer',
  Wave_Pounding: 'Wave Pounding',
  Wave_of_Despair: 'Wave of Despair',
  Winter_Harvest: 'Winter Harvest',
  World_Splitter: 'World Splitter',
  Zeus_Aid: 'Zeus\' Aid',
} as const;
